# Generated by Django 5.0.6 on 2025-09-01 16:39

import app.tenders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("tenders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tender",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Тендер",
                "verbose_name_plural": "Тендеры",
            },
        ),
        migrations.AlterModelOptions(
            name="tenderattachment",
            options={
                "verbose_name": "Вложение тендера",
                "verbose_name_plural": "Вложения тендеров",
            },
        ),
        migrations.AlterField(
            model_name="tender",
            name="admin_comment",
            field=models.TextField(
                blank=True,
                help_text="Комментарий администратора при отклонении",
                verbose_name="Комментарий администратора",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="attachments",
            field=models.JSONField(
                default=list,
                help_text="Список ссылок на файлы вложений",
                verbose_name="Вложения",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="budget_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Максимальный бюджет",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="budget_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Минимальный бюджет",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="categories.category", verbose_name="Категории"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="deadline_date",
            field=models.DateField(blank=True, null=True, verbose_name="Крайний срок"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "На модерации"),
                    ("APPROVED", "Одобрен"),
                    ("REJECTED", "Отклонен"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="tenderattachment",
            name="file",
            field=models.FileField(
                upload_to=app.tenders.models.tender_attachment_upload_path,
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="tenderattachment",
            name="file_size",
            field=models.PositiveIntegerField(verbose_name="Размер файла"),
        ),
        migrations.AlterField(
            model_name="tenderattachment",
            name="filename",
            field=models.CharField(max_length=255, verbose_name="Название файла"),
        ),
        migrations.AlterField(
            model_name="tenderattachment",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tender_attachments",
                to="tenders.tender",
                verbose_name="Тендер",
            ),
        ),
        migrations.AlterField(
            model_name="tenderattachment",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
        ),
    ]
