# Generated by Django 5.0.6 on 2025-09-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_status"),
        (
            "tenders",
            "0002_alter_tender_options_alter_tenderattachment_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenders",
                to="companies.company",
                verbose_name="Компания",
            ),
        ),
    ]
