# Generated by Django 5.0.6 on 2025-09-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0003_add_company_to_tender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="budget_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=30,
                null=True,
                verbose_name="Максимальный бюджет",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="budget_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=30,
                null=True,
                verbose_name="Минимальный бюджет",
            ),
        ),
    ]
