# Generated by Django 5.0.6 on 2025-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0004_remove_budget_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="currency",
            field=models.CharField(
                choices=[("KZT", "KZT"), ("USD", "USD"), ("RUB", "RUB")],
                default="KZT",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
    ]
