# Generated by Django 5.0.6 on 2025-09-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0005_tender_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Номер телефона для связи с автором тендера",
                max_length=20,
                null=True,
                verbose_name="Контактный телефон",
            ),
        ),
    ]
