# Generated by Django 5.0.6 on 2025-09-01 16:16

import app.ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Рекламное объявление",
                "verbose_name_plural": "Рекламные объявления",
            },
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="ends_at",
            field=models.DateTimeField(verbose_name="Окончание показа"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                upload_to=app.ads.models.ad_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="position",
            field=models.CharField(
                choices=[
                    ("HOME_WIDGET", "Баннер на главной странице"),
                    ("SIDEBAR", "Боковая панель"),
                    ("BANNER", "Полноширинный баннер"),
                ],
                max_length=20,
                verbose_name="Позиция показа",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="starts_at",
            field=models.DateTimeField(verbose_name="Начало показа"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="url",
            field=models.URLField(verbose_name="Ссылка"),
        ),
    ]
