# Generated by Django 5.0.6 on 2025-09-09 17:15

import app.ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_options_alter_ad_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                help_text="Загрузите изображение для рекламного баннера (поддерживаются все популярные форматы: JPG, PNG, GIF, WEBP)",
                upload_to=app.ads.models.ad_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
    ]
