# Generated by Django 5.0.6 on 2025-09-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Окончание показа"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало показа"
            ),
        ),
    ]
