# Generated by Django 5.0.6 on 2025-09-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_ad_ends_at_alter_ad_starts_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="status",
            field=models.CharField(
                choices=[("active", "Активно"), ("stopped", "Остановлено")],
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
