# Generated by Django 5.0.6 on 2025-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_ad_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="position",
            field=models.CharField(
                choices=[
                    ("HOME_WIDGET", "Баннер на главной странице"),
                    ("SIDEBAR_LEFT", "Боковая панель с левой стороны"),
                    ("SIDEBAR_RIGHT", "Боковая панель с правой стороны"),
                    ("BANNER", "Полноширинный баннер"),
                ],
                max_length=20,
                verbose_name="Позиция показа",
            ),
        ),
    ]
