# Generated by Django 5.0.6 on 2025-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_alter_ad_position"),
        ("products", "0008_product_on_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Товары, участвующие в данной акции",
                related_name="actions",
                to="products.product",
            ),
        ),
    ]
