# Generated by Django 5.0.6 on 2025-09-01 15:43

import app.companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="company",
            name="branches_count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество филиалов"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="categories.category", verbose_name="Категории"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="company",
            name="contacts",
            field=models.JSONField(
                default=dict,
                help_text="Номера телефонов, emails, веб-сайты",
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="company",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_info",
            field=models.JSONField(
                default=dict,
                help_text="Юридическая информация, ИНН, КПП и т.д.",
                verbose_name="Юридическая информация",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app.companies.models.logo_upload_path,
                validators=[app.companies.models.validate_logo_size],
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="payment_methods",
            field=models.JSONField(
                default=list,
                help_text="Доступные способы оплаты",
                verbose_name="Способы оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="rating",
            field=models.FloatField(default=0.0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="company",
            name="staff_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество сотрудников"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING", "На модерации"),
                    ("APPROVED", "Одобрено"),
                    ("BANNED", "Заблокировано"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="company",
            name="work_schedule",
            field=models.JSONField(
                default=dict, help_text="График работы", verbose_name="График работы"
            ),
        ),
    ]
