# Generated by Django 5.0.6 on 2025-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_company_options_alter_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING", "На модерации"),
                    ("APPROVED", "Одобрено"),
                    ("BANNED", "Заблокировано"),
                ],
                default="APPROVED",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
