# Generated by Django 5.0.6 on 2025-09-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="phones",
            field=models.CharField(
                blank=True,
                help_text="Номера телефонов через ; для импорта/экспорта",
                max_length=500,
                verbose_name="Номера телефонов",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="supplier_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEALER", "Дилер"),
                    ("MANUFACTURER", "Производитель"),
                    ("TRADE_REPRESENTATIVE", "Торговый представитель"),
                ],
                max_length=30,
                verbose_name="Тип поставщика",
            ),
        ),
    ]
