# Generated by Django 5.0.6 on 2025-09-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_phones_company_supplier_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(
                default="Казахстан", max_length=100, verbose_name="Страна"
            ),
        ),
    ]
