# Generated by Django 5.0.6 on 2025-09-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="actionlog",
            new_name="logs_action_user_id_03575c_idx",
            old_name="logs_actionlog_user_id_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="actionlog",
            new_name="logs_action_entity__9bdaab_idx",
            old_name="logs_actionlog_entity_type_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="actionlog",
            new_name="logs_action_created_45cebe_idx",
            old_name="logs_actionlog_created_at_idx",
        ),
    ]
