# Generated by Django 5.0.6 on 2025-09-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=4.5,
                help_text="Product rating from 4.0 to 5.0",
                max_digits=3,
            ),
        ),
    ]
