# Generated by Django 5.0.6 on 2025-09-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("KZT", "Kazakhstani Tenge"),
                    ("RUB", "Russian Ruble"),
                    ("USD", "US Dollar"),
                ],
                default="KZT",
                max_length=3,
            ),
        ),
    ]
