# Generated by Django 5.0.6 on 2025-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Основное изображение товара",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
