# Generated by Django 5.0.6 on 2025-09-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("companies", "0004_company_phones_company_supplier_type"),
        ("products", "0005_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KZT", "Kazakhstani Tenge"),
                            ("RUB", "Russian Ruble"),
                            ("USD", "US Dollar"),
                        ],
                        default="KZT",
                        max_length=3,
                    ),
                ),
                ("is_service", models.BooleanField(default=False)),
                (
                    "image_data",
                    models.JSONField(
                        default=dict, help_text="Данные основного изображения"
                    ),
                ),
                (
                    "images_data",
                    models.JSONField(
                        default=list, help_text="Данные дополнительных изображений"
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_products",
                        to="companies.company",
                    ),
                ),
                (
                    "pending_category",
                    models.ForeignKey(
                        help_text="Категория, которая ожидает модерации",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_products",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар на модерации",
                "verbose_name_plural": "Товары на модерации",
                "ordering": ["-created_at"],
            },
        ),
    ]
