# Generated by Django 5.0.6 on 2025-09-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_pendingproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingProduct",
        ),
    ]
