# Generated by Django 5.0.6 on 2025-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_delete_pendingproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(
                default=False, help_text="Товар участвует в акции/скидке"
            ),
        ),
    ]
